version: '3'
services:
  my-npm-app:
    build: .
    ports:
      - "3010:3010"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    command: ["node", "index.js"]
    working_dir: /usr/src/app  # Ensure the container runs from the correct directory
